- hosts: masters
  become: true
  gather_facts: false
  vars_files:
  - ./vars/main.yml
  tasks:

  - name: apt update
    apt:
      update_cache: true

  - name: apt upgrade
    apt:
      upgrade: yes

  - name: install Packages
    package:
      name:
      - net-tools
      - telnet

  - name: distribute /etc/hosts
    ansible.builtin.template:
      src: ./templates/etc-hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'
    become: yes

  - name: disable hosts auto update
    lineinfile:
      dest: /etc/cloud/cloud.cfg
      state: present
      regexp: '^ - update_hostname'
      line: '# - update_hostname'

  - name: Set timezone to Asia/Tokyo
    community.general.timezone:
      name: Asia/Tokyo
    become: true

  - name: install language-pack-ja
    apt: name={{ item }} update_cache=yes
    with_items:
    - language-pack-ja

  - name: create locale ja_JP.UTF-8
    locale_gen:
      name: ja_JP.UTF-8

  - name: change locale
    command: update-locale LANG=ja_JP.UTF-8

  - name: add sudoers
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: "{{ item.match }}"
      line: "{{ item.line }}"
    with_items:
    - { match: 'pi', line: 'pi ALL=(ALL) NOPASSWD: ALL' }

