- hosts: bation
  gather_facts: true
  become: yes
  become_method: sudo

  tasks:

  - name: install essencial packages
    package:
      name:
      - apt-transport-https
      - ca-certificates
      - rpcbind
      - curl
      - nfs-server
      - lsof

  - name: enable nfs-server systemd
    systemd:
      name: nfs-server
      daemon_reload: yes
      enabled: yes

  - name: install Google Cloud public signing key
    get_url:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
      mode: '0644'

  - name: add the Kubernetes apt repository
    lineinfile:
      path: /etc/apt/sources.list.d/kubernetes.list
      line: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
      create: yes

  - name: install containerd Kubernetes Packages
    apt:
      pkg:
      - docker.io
      - docker-compose
      - containerd
      - kubectl=1.21.7-00
      update_cache: yes

#  - name: install docker-compose
#    get_url:
#      url: "https://github.com/docker/compose/releases/download/2.12.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
#      dest: /usr/local/bin/docker-compose
#      mode: +x

  - name: Hold Kubernetes Packages
    dpkg_selections:
      name: '{{item}}'
      selection: hold
    with_items:
    - kubectl

  - name: add user 'pi' to docker group
    user:
      name: pi
      group: docker
      append: yes

