- hosts: masters
  gather_facts: false
  become: yes
  tasks:
  - name: distribute hosts
    copy:
      src: ~/mono_infra/file/glusterfs.conf
      dest: /etc/modules-load.d/glusterfs.conf
      owner: root
      group: root
      mode: 0644
