- hosts: masters
  gather_facts: true
  become: yes
  become_method: sudo

  tasks:
  - name: add download repository
    shell: 'dnf config-manager --add-repo=https://download.docker.com linux/centos/docker-ce.repo'
